### ISSUE TITLE
C:\\Users\\DELL\\Desktop\\Pyhton\\Energy.xlsx

### ISSUE THREAD

**Issue by serhanelmacioglu** [BeyzaErdogan/Derin-renme#1]
Beyza Hanım,

Merhabalar öncelikle siz ve sevdikleriniz umarım iyilerdir.

GitHub koymuş olduğunuz python uzantılı kodunuzu çalıştırmayı denemeden önce gözüme bir şey takıldı. 

[Veri çerçevesi(dataframe)](https://github.com/BeyzaErdogan/Derin-Ogrenme/blob/1c57e84eb4e4dbdfbd7e02007c00a3ceab7fd754/ysa.py#L19) kısmında belirlemiş olduğunuz bilgisayarınızdaki ilgili Excel dosyasını buraya eklememişsiniz sanırım. Ondan dolayı programı denemek isteyen kişiler çalıştıramayacaktır. İsterseniz onu buraya ekleyip sonrasında

> dataframe = pd.read_excel('\Energy.xlsx')

olarak kodunuzda değişiklik yapabilirsiniz.

_Not:_ Eğer Excel dosyanızı GitHub'a eklemek veya gizli tutmak istiyorsanız  ilgili kısma yorumda bulunursanız daha anlaşılır olacaktır.

Saygılarımla,

Serhan Elmacıoğlu

**Comment by BeyzaErdogan** [comment]
Merhaba Serhan Bey,

Çok teşekkür ederim. Umarım sizlerde iyisinizdir.

Dikkatimden kaçmış hemen ekliyorum. Uyarınız için çok teşekkür ederim.

Sevgiler ve saygılarımla,

Beyza Nur Erdoğan

Serhan Elmacıoğlu ***@***.***>, 20 Ağu 2021 Cum, 18:49
tarihinde şunu yazdı:
